-- Baseline schema for the Rackin sync backend.
-- Mirrors docs/architecture/backend-schema.md sections 3-5. The CHECK
-- constraints and defaults below are specified there but are not expressible
-- through the current JPA annotations, so Hibernate's ddl-auto would never
-- have created them.

CREATE TABLE member (
    -- Sequential string id (e.g. '1217'), assigned by whichever side creates
    -- the record first. Deliberately not a sequence: the tablet assigns ids
    -- fully offline in this same space (ADR-001 / backend-schema.md 7).
    id          VARCHAR(20)  PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    plan_type   VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    client_uuid UUID         NOT NULL,
    phone       VARCHAR(20),

    CONSTRAINT ck_member_plan_type CHECK (plan_type IN ('weekly', 'monthly'))
);

CREATE UNIQUE INDEX idx_member_client_uuid ON member (client_uuid);
CREATE INDEX idx_member_name ON member (name);

CREATE TABLE payment (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id    VARCHAR(20)    NOT NULL REFERENCES member (id),
    amount       NUMERIC(10, 2) NOT NULL,
    method       VARCHAR(20)    NOT NULL,
    paid_at      TIMESTAMPTZ    NOT NULL,
    -- Computed as paid_at + plan duration and stored, not recalculated on
    -- read, since it is immutable once written (backend-schema.md 4).
    covers_until TIMESTAMPTZ    NOT NULL,
    client_uuid  UUID           NOT NULL,

    CONSTRAINT ck_payment_amount CHECK (amount > 0),
    CONSTRAINT ck_payment_method CHECK (method IN ('cash', 'transfer'))
);

CREATE INDEX idx_payment_member_id ON payment (member_id);
CREATE INDEX idx_payment_covers_until ON payment (covers_until);
CREATE UNIQUE INDEX idx_payment_client_uuid ON payment (client_uuid);

CREATE TABLE check_in (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   VARCHAR(20) NOT NULL REFERENCES member (id),
    -- Quoted: the JPA field is named `timestamp` with no @Column override, and
    -- the name collides with the SQL type keyword.
    "timestamp" TIMESTAMPTZ NOT NULL,
    method      VARCHAR(20) NOT NULL,
    client_uuid UUID        NOT NULL,

    CONSTRAINT ck_check_in_method CHECK (method IN ('numpad', 'qr', 'search'))
);

CREATE INDEX idx_checkin_member_id ON check_in (member_id);
CREATE INDEX idx_checkin_timestamp ON check_in ("timestamp");
CREATE UNIQUE INDEX idx_checkin_client_uuid ON check_in (client_uuid);
