-- The Store tab's daily cash ledger (frontend Task 4 Store proposal,
-- Decisions/Web Becomes a Read-Only Dashboard) — Water/Treadmill/Stair
-- Incline sales and freeform income/expense entries. The tablet has been
-- selling these and posting them to POST /api/store since 2026-08-22; that
-- endpoint has never existed, so every Store transaction has been 404ing
-- and sitting permanently rejected in the outbox.
--
-- Not member-scoped: unlike payment/check_in, a Store sale has no member on
-- the other end (a water bottle, not a membership) — item_key/description
-- identify what was sold instead. Membership payments already fold into the
-- Store tab's own totals client-side by joining against the payment table
-- (store.js's getRegisterTransactions) rather than being duplicated here.
--
-- "Close register" (the tablet's counting-boundary marker) is purely local
-- device state (deviceState, same as the on-desk staff id) — nothing to
-- store server-side for it.

CREATE TABLE store_transaction (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(20)    NOT NULL,
    -- Which fixed/timed item this was (water, treadmill, stairIncline), or
    -- null for a freeform Log a Transaction entry — matches the tablet's own
    -- STORE_ITEMS/TIMED_ITEMS keys, not a foreign key: item definitions live
    -- on the tablet (ADR-001), not the backend.
    item_key     VARCHAR(40),
    description  VARCHAR(200)   NOT NULL,
    amount       NUMERIC(10, 2) NOT NULL,
    occurred_at  TIMESTAMPTZ    NOT NULL,
    client_uuid  UUID           NOT NULL,
    recorded_by_id   VARCHAR(64),
    recorded_by_name VARCHAR(100),

    CONSTRAINT ck_store_transaction_type CHECK (type IN ('income', 'expense')),
    CONSTRAINT ck_store_transaction_amount CHECK (amount > 0)
);

CREATE INDEX idx_store_transaction_occurred_at ON store_transaction (occurred_at);
CREATE UNIQUE INDEX idx_store_transaction_client_uuid ON store_transaction (client_uuid);
